clone/clone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("coin_app/", include("coin_app.api.urls")),
]

clone/coin_app/api/urls.py
from django.urls import path
from .views import home, CryptoDetailView,\
    home_price, home_symbol, home_percent_change_24h, home_percent_change_7d,\
    home_market_cap, home_volume_24h, home_circulating_supply,\
    search, PreciousMetalsListView, NewsListView, CryptoView

app_name = "coin_app"

urlpatterns = [
    path("home/", home, name="home_view"),
    path("home_price/", home_price, name="home_view_price"),
    path("home_symbol/", home_symbol, name="home_view_symbol"),
    path("home_percent_change_24h/", home_percent_change_24h, name="home_percent_change_24h"),
    path("home_percent_change_7d/", home_percent_change_7d, name="home_percent_change_7d"),
    path("home_market_cap/", home_market_cap, name="home_market_cap"),
    path("home_volume_24h/", home_volume_24h, name="home_volume_24h"),
    path("home_circulating_supply/", home_circulating_supply, name="home_circulating_supply"),
    path("detail_crypto/<int:pk>", CryptoDetailView.as_view(), name="detail_view"),
    path("search/", search, name='search_result'),
    path('precious-metals/', PreciousMetalsListView.as_view(), name='precious-metals-list'),
    path('news/', NewsListView.as_view(), name='news_list'),
    path('crypto_list/', CryptoView.as_view(), name='crypto_list')
]

clone/coin_app/models.py
from django.db import models

# Create your models here.


class CryptoModel(models.Model):
    name = models.TextField(max_length=100)
    symbol = models.TextField(max_length=100)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    percent_change_24h = models.DecimalField(max_digits=20, decimal_places=2)
    percent_change_7d = models.DecimalField(max_digits=20, decimal_places=2)
    market_cap = models.IntegerField()
    volume_24h = models.IntegerField()
    circulating_supply = models.IntegerField()

    def __str__(self):
        return f"{self.symbol}, {self.name}, \n{self.price}$ " \
               f"\n{self.percent_change_24h}%, \n{self.percent_change_7d}% " \
               f"\n{self.market_cap}$, \n{self.volume_24h}$, \n{self.circulating_supply} {self.symbol}"


class PreciousMetalsModel(models.Model):
    code = models.TextField(max_length=20)
    rate = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return f"{self.code}-{self.rate}"


class NewsModel(models.Model):
    title = models.TextField(max_length=200)
    author = models.TextField(max_length=100)
    published = models.DateField()
    url = models.URLField()

    def __str__(self):
        return f"{self.title} {self.author} {self.published} {self.url}"
    

clone/coin_app/api/forms.py
from django import forms
from ..models import CryptoModel


class SearchForm(forms.Form):
   q = forms.CharField(label = 'Search', max_length=50)

clone/coin_app/api/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, ListView
from ..models import CryptoModel, PreciousMetalsModel, NewsModel
from django.db.models import Q


# Create your views here.
def search(request):
    search_query = request.GET.get('q', '')
    posts = CryptoModel.objects.filter(Q(name__icontains=search_query) | Q(symbol__icontains=search_query))
    context = {'posts': posts, 'search_query': search_query}
    return render(request, 'coin_app/search.html', context)

def get_ordered_lists(order_by):
    crypto_list = CryptoModel.objects.order_by(order_by)
    metal_list = PreciousMetalsModel.objects.order_by("rate")
    news_list = NewsModel.objects.order_by("-published")[:5]
    context = {
        "access_crypto": crypto_list,
        "access_metal": metal_list,
        "access_news": news_list
    }
    return context


def home(request):
    context = get_ordered_lists("name")
    return render(request, "coin_app/home.html", context=context)


def home_symbol(request):
    context = get_ordered_lists("symbol")
    return render(request, "coin_app/home.html", context=context)


def home_price(request):
    context = get_ordered_lists("-price")
    return render(request, "coin_app/home.html", context=context)


def home_percent_change_24h(request):
    context = get_ordered_lists("-percent_change_24h")
    return render(request, "coin_app/home.html", context=context)


def home_percent_change_7d(request):
    context = get_ordered_lists("-percent_change_7d")
    return render(request, "coin_app/home.html", context=context)


def home_market_cap(request):
    context = get_ordered_lists("-market_cap")
    return render(request, "coin_app/home.html", context=context)


def home_volume_24h(request):
    context = get_ordered_lists("-volume_24h")
    return render(request, "coin_app/home.html", context=context)


def home_circulating_supply(request):
    context = get_ordered_lists("-circulating_supply")
    return render(request, "coin_app/home.html", context=context)


class CryptoDetailView(DetailView):
    context_object_name = "crypto_model"
    model = CryptoModel


def get_crypto_ordered_lists(order_by):
    crypto_list = CryptoModel.objects.order_by(order_by)
    context = {
        "crypto_list": crypto_list,
    }
    return context


class CryptoView(ListView):
    model = CryptoModel
    template_name = 'coin_app/crypto_list.html'
    context_object_name = 'crypto_list'
    ordering = ['market_cap']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order_by = self.request.GET.get('order_by', 'name')
        context.update(get_crypto_ordered_lists(order_by))
        return context


class PreciousMetalsListView(ListView):
    model = PreciousMetalsModel
    template_name = 'coin_app/precious_metals_list.html'
    context_object_name = 'metal_list'
    ordering = ['rate']


class NewsListView(ListView):
    model = NewsModel
    template_name = 'coin_app/news.html'
    context_object_name = "news_list"
    ordering = ['-published']

clone/coin_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView
from .models import CryptoModel
# Create your views here.


def home(request):
    crypto_list = CryptoModel.objects.order_by("name")
    crypto_dict = {"access_crypto": crypto_list}
    return render(request, "coin_app/home.html", context=crypto_dict)


class CryptoDetailView(DetailView):
    model = CryptoModel

clone/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Home</title>
  <link rel="stylesheet" href="{% static 'coin_app/style.css' %}">
  <title>Title</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<body>
{% csrf_token %}

<style>
    .navbar {
        margin-left: 1cm;
    }
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'coin_app:home_view' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'coin_app:crypto_list' %}">Cryptocurrency <span class="sr-only"></span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'coin_app:precious-metals-list' %}">Precious Metals <span class="sr-only"></span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'coin_app:news_list' %}">News</a>
      </li>

    </ul>
    <form class="search-bar s-active" action="{% url 'coin_app:search_result' %}" method="GET">
      <div class="input-group">
        <input class="form-control" type="text" placeholder="Search cryptocurrency" aria-label="Search" name="q" value="{{ search_query }}">
        <div class="input-group-append">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </div>
      </div>
    </form>
  </div>
</nav>

<div class="container">

  {% block content %}

  {% endblock %}
</div>
</body>
</html>

clone/templates/coin_app/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Home</title>
  <link rel="stylesheet" href="{% static 'coin_app/style.css' %}">
  <title>Title</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<body>
{% csrf_token %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'coin_app:home_view' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'coin_app:crypto_list' %}">Cryptocurrency <span class="sr-only"></span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'coin_app:precious-metals-list' %}">Precious Metals <span class="sr-only"></span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'coin_app:news_list' %}">News</a>
      </li>

    </ul>
    <form class="search-bar s-active" action={% url 'coin_app:search_result' %} method='GET'>
    <input class="form-control mr-sm-2" type="text" placeholder="Search cryptocurrency" aria-label="Search" name="q" value={{search_query}}>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<div class="container">

  {% block content %}

  {% endblock %}
</div>
</body>
</html>

clone/templates/coin_app/crypto_list.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block content %}

<div class="h-100 d-inline-block">
    {% if crypto_list %}
    <table class="table">
        <thead>
        <tr>
            <th><a href="{% url 'coin_app:crypto_list' %}?order_by=name">Crypto Name</a></th>
            <th><a href="{% url 'coin_app:crypto_list' %}?order_by=symbol">Symbol</a></th>
            <th><a href="{% url 'coin_app:crypto_list' %}?order_by=-price">Price</a></th>
            <th><a href="{% url 'coin_app:crypto_list' %}?order_by=-percent_change_24h">Percent Change 24h</a></th>
            <th><a href="{% url 'coin_app:crypto_list' %}?order_by=-percent_change_7d">Percent Change 7d</a></th>
            <th><a href="{% url 'coin_app:crypto_list' %}?order_by=-market_cap">Market Cap</a></th>
            <th><a href="{% url 'coin_app:crypto_list' %}?order_by=-volume_24h">Volume 24h</a></th>
            <th><a href="{% url 'coin_app:crypto_list' %}?order_by=-circulating_supply">Circulating Supply</a></th>
        </tr>
        <thead>
        {% for bbc in crypto_list %}
        <tr>
            <td><a href="/coin_app/detail_crypto/{{bbc.id}}">{{ bbc.name }}</a></td>
            <td><a href="/coin_app/detail_crypto/{{bbc.id}}">{{ bbc.symbol }}</a></td>
            <td><a href="/coin_app/detail_crypto/{{bbc.id}}">${{ bbc.price }}</a></td>
            <td><a href="/coin_app/detail_crypto/{{bbc.id}}">{{ bbc.percent_change_24h }}%</a></td>
            <td><a href="/coin_app/detail_crypto/{{bbc.id}}">{{ bbc.percent_change_7d }}%</a></td>
            <td><a href="/coin_app/detail_crypto/{{bbc.id}}">${{ bbc.market_cap }}</a></td>
            <td><a href="/coin_app/detail_crypto/{{bbc.id}}">${{ bbc.volume_24h }}</a></td>
            <td><a href="/coin_app/detail_crypto/{{bbc.id}}">{{ bbc.circulating_supply }} {{ bbc.symbol }}</a></td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>NO CRYPTO TO DISPLAY</p>

    {% endif %}
</div>


{% endblock %}

clone/templates/coin_app/cryptomodel_detail.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block content %}

<h2>Detail view</h2>
<h2>Name : {{crypto_model.name}}</h2>
<h2>Symbol : {{ crypto_model.symbol }}</h2>
<h2>Price : ${{ crypto_model.price }}</h2>
<h2>Percent price change in 24h : {{ crypto_model.percent_change_24h }}%</h2>
<h2>Percent price change in 7d : {{ crypto_model.percent_change_7d }}%</h2>
<h2>Market cap : ${{ crypto_model.market_cap }}</h2>
<h2>Volume 24h : ${{ crypto_model.volume_24h }}</h2>
<h2>Circular supply : {{ crypto_model.circulating_supply }} {{ crypto_model.symbol }}</h2>



{% endblock %}

clone/templates/coin_app/home.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <table class="table">
            <h1>Precious Metals</h1>
            <p>Price per once</p>
            <ul>
                {% for metal in access_metal %}
                <li>{{ metal.code }} - ${{ metal.rate }}</li>
                {% endfor %}
            </ul>
        </table>

    </div>
    <div class="col-md-6">
        {% if access_crypto %}
        <table class="table">
            <h1>News</h1>
            <ul>
                {% for news in access_news %}
                <li><a href="{{ news.url }}">{{ news.title }}</a> </li>
                {% endfor %}
            </ul>
        </table>
        {% endif %}
    </div>
</div>

    <div class="h-100 d-inline-block">
    {% if access_crypto %}
    <table class="table">
        <thead>
            <tr>
                <th><a href="/coin_app/home">Crypto Name</a></th>
                <th><a href="/coin_app/home">Symbol</a></th>
                <th><a href="/coin_app/home_price">Price</a></th>
                <th><a href="/coin_app/home_percent_change_24h">Percent Change 24h</a></th>
                <th><a href="/coin_app/home_percent_change_7d">Percent Change 7d</a></th>
                <th><a href="/coin_app/home_market_cap">Market Cap</a></th>
                <th><a href="/coin_app/home_volume_24h">Volume 24h</a></th>
                <th><a href="/coin_app/home_circulating_supply">Circulating Supply</a></th>
            </tr>
        <thead>
        {% for bbc in access_crypto %}
        <tr>
            <td><a href="/coin_app/detail_crypto/{{bbc.id}}">{{ bbc.name }}</a></td>
            <td><a href="/coin_app/detail_crypto/{{bbc.id}}">{{ bbc.symbol }}</a></td>
            <td><a href="/coin_app/detail_crypto/{{bbc.id}}">${{ bbc.price }}</a></td>
            <td><a href="/coin_app/detail_crypto/{{bbc.id}}">{{ bbc.percent_change_24h }}%</a></td>
            <td><a href="/coin_app/detail_crypto/{{bbc.id}}">{{ bbc.percent_change_7d }}%</a></td>
            <td><a href="/coin_app/detail_crypto/{{bbc.id}}">${{ bbc.market_cap }}</a></td>
            <td><a href="/coin_app/detail_crypto/{{bbc.id}}">${{ bbc.volume_24h }}</a></td>
            <td><a href="/coin_app/detail_crypto/{{bbc.id}}">{{ bbc.circulating_supply }} {{ bbc.symbol }}</a></td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>NO CRYPTO TO DISPLAY</p>

    {% endif %}
    </div>


{% endblock %}

clone/templates/coin_app/news.html
{% extends 'base.html' %}

{% block content %}
    <h1>News</h1>
    <ul>
        {% for news in news_list %}
            <li><a href="{{ news.url }}">{{news.title}}, {{news.author}}, {{news.published}} </a></li>
        {% empty %}
            <li>No news today.</li>
        {% endfor %}
    </ul>

{% endblock %}

clone/templates/coin_app/precious_metals_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Precious Metals List</h1>
  <p>Price per once</p>
  <ul>
    {% for metal in metal_list %}
      <li>{{ metal.code }} - ${{ metal.rate }}</li>
    {% empty %}
      <li>No metals available.</li>
    {% endfor %}
  </ul>
{% endblock %}

clone/templates/coin_app/search.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block content %}

{% if posts %}
<h2>Search result</h2>
    {% for crypto_model in posts %}    
    <h2>Name : {{crypto_model.name}}</h2>
    <h2>Symbol : {{ crypto_model.symbol }}</h2>
    <h2>Price : {{ crypto_model.price }}$</h2>
    <h2>Percent price change in 24h : {{ crypto_model.percent_change_24h }}%</h2>
    <h2>Percent price change in 7d : {{ crypto_model.percent_change_7d }}%</h2>
    <h2>Market cap : {{ crypto_model.market_cap }}$</h2>
    <h2>Volume 24h : {{ crypto_model.volume_24h }}$</h2>
    <h2>Circular supply : {{ crypto_model.circulating_supply }} {{ crypto_model.symbol }}</h2>
    <p>  
        <br>
    </p>
    {% endfor %}
{% else %}
    <h2>No crypto found!!!</h2>
{% endif%}

{% endblock %}